// src/routes/auth.js
//
// Auth routes — provider-specific sign-in happens outside the API; the API verifies ID tokens and exposes session information.
// These routes cover the parts that stay in the Express app:
//
//   GET  /api/auth/industries  — public, used by frontend industry picker
//   GET  /api/auth/me          — returns current user + org from token

const express = require("express");
const db = require("../db/repository");
const { requireAuth, requireAuthIdentityOnly, isPlatformAdminIdentity } = require("../middleware/auth");
const industryPacks = require("../seed/industryPacks");
const platformAdmin = require("../platform/admin");
const { getLogger } = require("../observability/logger");
const log = getLogger("routes.auth");

const router = express.Router();

// GET /api/auth/login-url?redirect_uri=<url> — public
// In dev, Keycloak can provide an OIDC authorization URL. In production,
// Identity Platform authentication is initiated by the frontend SDK.
router.get("/login-url", (req, res) => {
  const provider = (process.env.AUTH_PROVIDER || "cognito").toLowerCase();

  if (provider === "identity_platform") {
    // Identity Platform authentication is initiated by the frontend SDK.
    // The backend only verifies the resulting ID token. No client secret or
    // Google OAuth authorization URL is generated by this API.
    return res.json({ provider: "identity_platform", devMode: false, loginUrl: null });
  }

  const keycloakUrl = process.env.KEYCLOAK_URL;
  const realm       = process.env.KEYCLOAK_REALM || "master";
  const clientId    = process.env.KEYCLOAK_CLIENT_ID || "chiefvoice-app";
  const redirectUri = req.query.redirect_uri;

  if (!keycloakUrl) {
    return res.json({ provider: "keycloak", devMode: true, loginUrl: null });
  }
  if (!redirectUri) {
    return res.status(400).json({ error: "redirect_uri query param is required" });
  }

  const params = new URLSearchParams({
    client_id: clientId,
    response_type: "code",
    scope: "openid email profile",
    redirect_uri: redirectUri,
  });

  const loginUrl = `${keycloakUrl}/realms/${realm}/protocol/openid-connect/auth?${params}`;
  res.json({ provider: "keycloak", loginUrl });
});

// GET /api/auth/industries — public
router.get("/industries", (_req, res) => {
  res.json(industryPacks.listIndustries());
});

// GET /api/auth/workspaces — every workspace the current user belongs to.
// This endpoint intentionally ignores the selected-workspace header so a
// stale workspace selection can never hide the user's other workspaces.
router.get("/workspaces", requireAuthIdentityOnly, async (req, res) => {
  try {
    if (isPlatformAdminIdentity(req.authClaims, req.userEmail)) {
      const organizations = await platformAdmin.listOrganizations();
      return res.json((organizations || []).map((org) => ({
        membershipId: null,
        orgId: org.id,
        role: "Super Admin",
        name: req.userName || req.userEmail || "Platform Admin",
        featureFlags: org.featureFlags || [],
        organization: {
          id: org.id,
          name: org.name,
          workspaceName: org.workspaceName,
          industry: org.industry,
          status: org.status,
        },
      })));
    }

    const workspaces = await db.listMembershipsForUser(req.userId, req.userEmail);
    res.json(workspaces);
  } catch (err) {
    log.error("❌ /api/auth/workspaces:", err.message);
    res.status(500).json({ error: "Failed to load workspaces" });
  }
});

// GET /api/auth/me — returns the authenticated user and their org
router.get("/me", requireAuth, async (req, res) => {
  try {
    const org = await db.getOrg(req.orgId);
    res.json({
      user: { id: req.userId, email: req.userEmail, name: req.userName, role: req.userRole },
      org,
    });
  } catch (err) {
    log.error("❌ /api/auth/me:", err.message);
    res.status(500).json({ error: "Failed to load session" });
  }
});

module.exports = router;
