// src/routes/auth.js
//
// Auth routes — provider-specific sign-in happens outside the API; the API verifies ID tokens and exposes session information.
// These routes cover the parts that stay in the Express app:
//
//   GET  /api/auth/industries  — public, used by frontend industry picker
//   GET  /api/auth/me          — returns current user + org from token

const express = require("express");
const db = require("../db/repository");
const { requireAuth, requireAuthIdentityOnly, isPlatformAdminIdentity } = require("../middleware/auth");
const industryPacks = require("../seed/industryPacks");
const workspaceRepository = require("../db/repositories/workspaceRepository");
const policy = require("../authorization/policy");
const platformAdmin = require("../platform/admin");
const { getLogger } = require("../observability/logger");
const { multipleWorkspacesEnabled } = require("../workspaces/capabilities");
const log = getLogger("routes.auth");

const router = express.Router();

// GET /api/auth/login-url?redirect_uri=<url> — public
// In dev, Keycloak can provide an OIDC authorization URL. In production,
// Identity Platform authentication is initiated by the frontend SDK.
router.get("/login-url", (req, res) => {
  const provider = (process.env.AUTH_PROVIDER || "cognito").toLowerCase();

  if (provider === "identity_platform") {
    // Identity Platform authentication is initiated by the frontend SDK.
    // The backend only verifies the resulting ID token. No client secret or
    // Google OAuth authorization URL is generated by this API.
    return res.json({ provider: "identity_platform", devMode: false, loginUrl: null });
  }

  const keycloakUrl = process.env.KEYCLOAK_URL;
  const realm       = process.env.KEYCLOAK_REALM || "master";
  const clientId    = process.env.KEYCLOAK_CLIENT_ID || "chiefvoice-app";
  const redirectUri = req.query.redirect_uri;

  if (!keycloakUrl) {
    return res.json({ provider: "keycloak", devMode: true, loginUrl: null });
  }
  if (!redirectUri) {
    return res.status(400).json({ error: "redirect_uri query param is required" });
  }

  const params = new URLSearchParams({
    client_id: clientId,
    response_type: "code",
    scope: "openid email profile",
    redirect_uri: redirectUri,
  });

  const loginUrl = `${keycloakUrl}/realms/${realm}/protocol/openid-connect/auth?${params}`;
  res.json({ provider: "keycloak", loginUrl });
});

// GET /api/auth/industries — public
router.get("/industries", (_req, res) => {
  res.json(industryPacks.listIndustries());
});

// GET /api/auth/workspaces — every workspace the current user belongs to.
// This endpoint intentionally ignores the selected-workspace header so a
// stale workspace selection can never hide the user's other workspaces.
router.get("/workspaces", requireAuthIdentityOnly, async (req, res) => {
  try {
    if (isPlatformAdminIdentity(req.authClaims, req.userEmail)) {
      const organizations = await platformAdmin.listOrganizations();
      const rows = [];
      for (const org of organizations || []) {
        const workspaces = multipleWorkspacesEnabled()
          ? await workspaceRepository.listForOrg(org.id)
          : [await workspaceRepository.getDefault(org.id)];
        for (const workspace of workspaces.filter(Boolean)) rows.push({
          membershipId: null, orgId: org.id, workspaceId: workspace.id, workspace,
          role: "Super Admin", workspaceRole: "Workspace Admin",
          name: req.userName || req.userEmail || "Platform Admin",
          featureFlags: org.featureFlags || [],
          organization: { id: org.id,name: org.name,workspaceName: org.workspaceName,industry: org.industry,status: org.status },
        });
      }
      return res.json(rows);
    }

    const workspaces = await db.listMembershipsForUser(req.userId, req.userEmail);
    const rows = [];
    for (const membership of workspaces) {
      if (membership.membershipId) await workspaceRepository.ensureDefaultMembership(membership.orgId, membership.membershipId);
      const available = multipleWorkspacesEnabled()
        ? await workspaceRepository.listForMember(membership.orgId,membership.membershipId)
        : [await workspaceRepository.getDefault(membership.orgId)];
      for (const workspace of available.filter(Boolean)) rows.push({
        ...membership,workspaceId:workspace.id,workspace,
        workspaceRole:workspace.role || (workspace.isDefault ? membership.role : null),
      });
    }
    res.json(rows);
  } catch (err) {
    log.error("❌ /api/auth/workspaces:", err.message);
    res.status(500).json({ error: "Failed to load workspaces" });
  }
});

router.get('/roles',requireAuth,(req,res) => res.json({
  organizationRoles: policy.ORGANIZATION_ROLES,workspaceRoles: policy.WORKSPACE_ROLES,
  authorization: req.authorization,
}));

// GET /api/auth/me — returns the authenticated user and their org
router.get("/me", requireAuth, async (req, res) => {
  try {
    const org = await db.getOrg(req.orgId);
    const activeWorkspace = await workspaceRepository.getActive(req.orgId,req.workspaceId);
    if (activeWorkspace) delete activeWorkspace.settings;
    res.json({
      user: { id: req.userId, email: req.userEmail, name: req.userName, role: req.userRole },
      org: org ? { id: org.id,name: org.name,status: org.status,industry: org.industry,
        workspaceName: org.workspaceName,subscriptionPlan: org.subscriptionPlan } : null,
      authorization: req.authorization,
      workspace: activeWorkspace,
      workspaceCapabilities: { multipleWorkspaces: multipleWorkspacesEnabled(), sharing: false },
    });
  } catch (err) {
    log.error("❌ /api/auth/me:", err.message);
    res.status(500).json({ error: "Failed to load session" });
  }
});

module.exports = router;
