// Durable command processing, usage holds, postpaid accounting, invoices and
// notification delivery state. This migration follows the billing foundation
// (2026100712) and credit ledger (2026100713). Keep all history restrictively
// owned: financial rows must never disappear through a cascading delete.
const orgAccountFk = (table) => `CONSTRAINT fk_${table}_org_account
  FOREIGN KEY (org_id) REFERENCES organization_billing_accounts(org_id)`;

module.exports = {
  id: '2026100714_billing_operations',
  steps: [
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_command_operations (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        operation_type VARCHAR(96) NOT NULL,
        idempotency_key VARCHAR(191) NOT NULL,
        request_fingerprint CHAR(64) NOT NULL,
        status VARCHAR(24) NOT NULL,
        result_json JSON NULL,
        error_code VARCHAR(96) NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        completed_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_command_operations_org_id (org_id,id),
        UNIQUE KEY uq_billing_command_operations_key (org_id,idempotency_key),
        KEY idx_billing_command_operations_status (org_id,status,created_at),
        ${orgAccountFk('billing_command_operations')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_outbox (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        event_key VARCHAR(191) NOT NULL,
        event_type VARCHAR(128) NOT NULL,
        schema_version SMALLINT UNSIGNED NOT NULL,
        aggregate_type VARCHAR(96) NOT NULL,
        aggregate_id VARCHAR(191) NOT NULL,
        aggregate_version BIGINT UNSIGNED NOT NULL,
        partition_key VARCHAR(64) NOT NULL,
        correlation_id VARCHAR(191) NULL,
        causation_id VARCHAR(191) NULL,
        payload_json JSON NOT NULL,
        status VARCHAR(24) NOT NULL DEFAULT 'pending',
        available_at DATETIME(6) NOT NULL,
        attempts INT UNSIGNED NOT NULL DEFAULT 0,
        lease_owner VARCHAR(191) NULL,
        lease_token VARCHAR(191) NULL,
        fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
        lease_expires_at DATETIME(6) NULL,
        completed_at DATETIME(6) NULL,
        last_error_code VARCHAR(96) NULL,
        last_error_at DATETIME(6) NULL,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_outbox_org_id (org_id,id),
        UNIQUE KEY uq_billing_outbox_event_key (org_id,event_key),
        KEY idx_billing_outbox_partition_claim (partition_key,status,available_at,id),
        KEY idx_billing_outbox_claim (status,available_at,id),
        KEY idx_billing_outbox_lease (status,lease_expires_at,id),
        KEY idx_billing_outbox_aggregate (org_id,aggregate_type,aggregate_id,aggregate_version),
        ${orgAccountFk('billing_outbox')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_consumer_inbox (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        consumer_key VARCHAR(128) NOT NULL,
        event_id VARCHAR(191) NOT NULL,
        event_type VARCHAR(128) NOT NULL,
        status VARCHAR(24) NOT NULL DEFAULT 'received',
        attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
        first_seen_at DATETIME(6) NOT NULL,
        processed_at DATETIME(6) NULL,
        last_error_code VARCHAR(96) NULL,
        last_error_at DATETIME(6) NULL,
        result_reference VARCHAR(191) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_consumer_inbox_org_id (org_id,id),
        UNIQUE KEY uq_billing_consumer_inbox_event (org_id,consumer_key,event_id),
        KEY idx_billing_consumer_inbox_status (org_id,consumer_key,status,first_seen_at),
        ${orgAccountFk('billing_consumer_inbox')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_reservations (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        workspace_id VARCHAR(191) NOT NULL,
        usage_operation_id VARCHAR(191) NOT NULL,
        source_revision VARCHAR(96) NOT NULL DEFAULT '0',
        funding_policy_version VARCHAR(96) NOT NULL,
        funding_snapshot_json JSON NOT NULL,
        status VARCHAR(24) NOT NULL,
        valid_until DATETIME(6) NOT NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        closed_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_reservations_org_id (org_id,id),
        UNIQUE KEY uq_billing_reservations_usage (org_id,workspace_id,usage_operation_id,source_revision),
        KEY idx_billing_reservations_due (org_id,status,valid_until,id),
        KEY idx_billing_reservations_workspace (org_id,workspace_id,status,created_at),
        CONSTRAINT fk_billing_reservations_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_reservations_workspace FOREIGN KEY (org_id,workspace_id)
          REFERENCES workspaces(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_reservation_lines (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        reservation_id VARCHAR(191) NOT NULL,
        line_number INT UNSIGNED NOT NULL,
        funding_source VARCHAR(24) NOT NULL,
        credit_position_id VARCHAR(191) NULL,
        credit_grant_id VARCHAR(191) NULL,
        credit_account_id VARCHAR(191) NULL,
        period_id VARCHAR(191) NULL,
        amount_units BIGINT UNSIGNED NOT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        held_units BIGINT UNSIGNED NOT NULL,
        consumed_units BIGINT UNSIGNED NOT NULL DEFAULT 0,
        released_units BIGINT UNSIGNED NOT NULL DEFAULT 0,
        funding_snapshot_json JSON NOT NULL,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_reservation_lines_org_id (org_id,id),
        UNIQUE KEY uq_billing_reservation_lines_number (org_id,reservation_id,line_number),
        KEY idx_billing_reservation_lines_position (org_id,credit_position_id),
        KEY idx_billing_reservation_lines_grant (org_id,credit_grant_id,asset,scale),
        KEY idx_billing_reservation_lines_account (org_id,credit_account_id,asset,scale),
        KEY idx_billing_reservation_lines_period (org_id,period_id),
        CONSTRAINT fk_billing_reservation_lines_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_reservation_lines_reservation FOREIGN KEY (org_id,reservation_id)
          REFERENCES billing_reservations(org_id,id),
        CONSTRAINT fk_billing_reservation_lines_position FOREIGN KEY (org_id,credit_position_id,asset,scale)
          REFERENCES billing_credit_positions(org_id,id,asset,scale),
        CONSTRAINT fk_billing_reservation_lines_grant FOREIGN KEY (org_id,credit_grant_id,asset,scale)
          REFERENCES billing_credit_grants(org_id,id,asset,scale),
        CONSTRAINT fk_billing_reservation_lines_account FOREIGN KEY (org_id,credit_account_id,asset,scale)
          REFERENCES billing_credit_accounts(org_id,id,asset,scale),
        CONSTRAINT fk_billing_reservation_lines_period FOREIGN KEY (org_id,period_id)
          REFERENCES billing_periods(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_postpaid_accounts (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        scope_type VARCHAR(24) NOT NULL,
        scope_owner_id VARCHAR(191) NOT NULL,
        workspace_id VARCHAR(191) NULL,
        enabled TINYINT UNSIGNED NOT NULL DEFAULT 0,
        limit_units BIGINT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        effective_at DATETIME(6) NOT NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_postpaid_accounts_org_id (org_id,id),
        UNIQUE KEY uq_billing_postpaid_accounts_scope (org_id,scope_type,scope_owner_id),
        KEY idx_billing_postpaid_accounts_enabled (org_id,scope_type,enabled,scope_owner_id),
        CONSTRAINT fk_billing_postpaid_accounts_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_postpaid_accounts_workspace FOREIGN KEY (org_id,workspace_id)
          REFERENCES workspaces(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_postpaid_period_totals (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        scope_type VARCHAR(24) NOT NULL,
        scope_owner_id VARCHAR(191) NOT NULL,
        workspace_id VARCHAR(191) NULL,
        period_id VARCHAR(191) NOT NULL,
        settled_units BIGINT NOT NULL DEFAULT 0,
        reserved_units BIGINT UNSIGNED NOT NULL DEFAULT 0,
        limit_units BIGINT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_postpaid_period_totals_org_id (org_id,id),
        UNIQUE KEY uq_billing_postpaid_period_totals_scope (org_id,period_id,scope_type,scope_owner_id),
        KEY idx_billing_postpaid_period_totals_period (org_id,period_id,scope_type,scope_owner_id),
        CONSTRAINT fk_billing_postpaid_period_totals_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_postpaid_period_totals_workspace FOREIGN KEY (org_id,workspace_id)
          REFERENCES workspaces(org_id,id),
        CONSTRAINT fk_billing_postpaid_period_totals_period FOREIGN KEY (org_id,period_id)
          REFERENCES billing_periods(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_postpaid_journals (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        workspace_id VARCHAR(191) NOT NULL,
        period_id VARCHAR(191) NOT NULL,
        reservation_id VARCHAR(191) NULL,
        operation_id VARCHAR(191) NOT NULL,
        entry_key VARCHAR(191) NOT NULL,
        entry_type VARCHAR(32) NOT NULL,
        amount_units BIGINT NOT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        occurred_at DATETIME(6) NOT NULL,
        actor_id VARCHAR(191) NULL,
        reason_code VARCHAR(96) NULL,
        reversal_of_id VARCHAR(191) NULL,
        metadata_json JSON NULL,
        created_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_postpaid_journals_org_id (org_id,id),
        UNIQUE KEY uq_billing_postpaid_journals_entry (org_id,entry_key),
        KEY idx_billing_postpaid_journals_workspace (org_id,workspace_id,occurred_at,id),
        KEY idx_billing_postpaid_journals_period (org_id,period_id,occurred_at,id),
        KEY idx_billing_postpaid_journals_operation (org_id,operation_id),
        CONSTRAINT fk_billing_postpaid_journals_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_postpaid_journals_workspace FOREIGN KEY (org_id,workspace_id)
          REFERENCES workspaces(org_id,id),
        CONSTRAINT fk_billing_postpaid_journals_period FOREIGN KEY (org_id,period_id)
          REFERENCES billing_periods(org_id,id),
        CONSTRAINT fk_billing_postpaid_journals_reservation FOREIGN KEY (org_id,reservation_id)
          REFERENCES billing_reservations(org_id,id),
        CONSTRAINT fk_billing_postpaid_journals_reversal FOREIGN KEY (org_id,reversal_of_id)
          REFERENCES billing_postpaid_journals(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_invoices (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        invoice_number VARCHAR(96) NOT NULL,
        period_id VARCHAR(191) NULL,
        status VARCHAR(24) NOT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        subtotal_units BIGINT NOT NULL,
        tax_units BIGINT NOT NULL DEFAULT 0,
        total_units BIGINT NOT NULL,
        paid_units BIGINT NOT NULL DEFAULT 0,
        issued_at DATETIME(6) NULL,
        due_at DATETIME(6) NULL,
        paid_at DATETIME(6) NULL,
        voided_at DATETIME(6) NULL,
        terms_snapshot_json JSON NOT NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_invoices_org_id (org_id,id),
        UNIQUE KEY uq_billing_invoices_number (org_id,invoice_number),
        KEY idx_billing_invoices_status_due (org_id,status,due_at,id),
        KEY idx_billing_invoices_period (org_id,period_id),
        CONSTRAINT fk_billing_invoices_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_invoices_period FOREIGN KEY (org_id,period_id)
          REFERENCES billing_periods(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_invoice_lines (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        invoice_id VARCHAR(191) NOT NULL,
        line_number INT UNSIGNED NOT NULL,
        line_key VARCHAR(191) NOT NULL,
        workspace_id VARCHAR(191) NULL,
        source_type VARCHAR(48) NOT NULL,
        source_id VARCHAR(191) NULL,
        source_revision VARCHAR(96) NULL,
        description_snapshot VARCHAR(512) NOT NULL,
        workspace_snapshot_json JSON NULL,
        line_snapshot_json JSON NOT NULL,
        amount_units BIGINT NOT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        created_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_invoice_lines_org_id (org_id,id),
        UNIQUE KEY uq_billing_invoice_lines_number (org_id,invoice_id,line_number),
        UNIQUE KEY uq_billing_invoice_lines_key (org_id,invoice_id,line_key),
        UNIQUE KEY uq_billing_invoice_lines_source (org_id,source_type,source_id,source_revision),
        KEY idx_billing_invoice_lines_workspace (org_id,workspace_id,invoice_id),
        CONSTRAINT fk_billing_invoice_lines_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_invoice_lines_invoice FOREIGN KEY (org_id,invoice_id)
          REFERENCES billing_invoices(org_id,id),
        CONSTRAINT fk_billing_invoice_lines_workspace FOREIGN KEY (org_id,workspace_id)
          REFERENCES workspaces(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_invoice_payments (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        invoice_id VARCHAR(191) NOT NULL,
        payment_request_id VARCHAR(191) NULL,
        idempotency_key VARCHAR(191) NOT NULL,
        amount_units BIGINT UNSIGNED NOT NULL,
        asset VARCHAR(32) NOT NULL,
        scale TINYINT UNSIGNED NOT NULL,
        status VARCHAR(24) NOT NULL,
        applied_at DATETIME(6) NULL,
        created_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_invoice_payments_org_id (org_id,id),
        UNIQUE KEY uq_billing_invoice_payments_key (org_id,idempotency_key),
        KEY idx_billing_invoice_payments_invoice (org_id,invoice_id,status,created_at),
        KEY idx_billing_invoice_payments_request (org_id,payment_request_id),
        CONSTRAINT fk_billing_invoice_payments_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_invoice_payments_invoice FOREIGN KEY (org_id,invoice_id)
          REFERENCES billing_invoices(org_id,id),
        CONSTRAINT fk_billing_invoice_payments_request FOREIGN KEY (org_id,payment_request_id)
          REFERENCES billing_payment_requests(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_notification_policies (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        scope_type VARCHAR(24) NOT NULL,
        scope_owner_id VARCHAR(191) NOT NULL,
        event_key VARCHAR(96) NOT NULL,
        amount_threshold_units BIGINT UNSIGNED NULL,
        percentage_threshold_bps SMALLINT UNSIGNED NULL,
        recovery_amount_units BIGINT UNSIGNED NULL,
        recovery_percentage_bps SMALLINT UNSIGNED NULL,
        cooldown_seconds INT UNSIGNED NOT NULL DEFAULT 0,
        enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
        policy_json JSON NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        updated_by VARCHAR(191) NULL,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_notification_policies_org_id (org_id,id),
        UNIQUE KEY uq_billing_notification_policies_scope_event (org_id,scope_type,scope_owner_id,event_key),
        KEY idx_billing_notification_policies_event (org_id,event_key,enabled),
        ${orgAccountFk('billing_notification_policies')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_contacts (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        user_id VARCHAR(191) NULL,
        email VARCHAR(320) NOT NULL,
        display_name VARCHAR(191) NULL,
        status VARCHAR(24) NOT NULL DEFAULT 'pending_verification',
        verification_token_hash CHAR(64) NULL,
        verified_at DATETIME(6) NULL,
        disabled_at DATETIME(6) NULL,
        notification_preferences_json JSON NULL,
        created_by VARCHAR(191) NULL,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_contacts_org_id (org_id,id),
        UNIQUE KEY uq_billing_contacts_email (org_id,email),
        KEY idx_billing_contacts_verified (org_id,status,verified_at),
        KEY idx_billing_contacts_user (org_id,user_id,status),
        ${orgAccountFk('billing_contacts')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_alert_states (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        policy_id VARCHAR(191) NULL,
        scope_type VARCHAR(24) NOT NULL,
        scope_owner_id VARCHAR(191) NOT NULL,
        event_key VARCHAR(96) NOT NULL,
        threshold_key VARCHAR(96) NOT NULL,
        state VARCHAR(24) NOT NULL DEFAULT 'clear',
        last_observed_units BIGINT NULL,
        last_observed_limit_units BIGINT NULL,
        crossing_sequence BIGINT UNSIGNED NOT NULL DEFAULT 0,
        crossed_at DATETIME(6) NULL,
        recovered_at DATETIME(6) NULL,
        next_eligible_at DATETIME(6) NULL,
        version BIGINT UNSIGNED NOT NULL DEFAULT 1,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_alert_states_org_id (org_id,id),
        UNIQUE KEY uq_billing_alert_states_scope (org_id,scope_type,scope_owner_id,event_key,threshold_key),
        KEY idx_billing_alert_states_due (org_id,state,next_eligible_at),
        CONSTRAINT fk_billing_alert_states_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_alert_states_policy FOREIGN KEY (org_id,policy_id)
          REFERENCES billing_notification_policies(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_notifications (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        notification_key VARCHAR(191) NOT NULL,
        event_key VARCHAR(96) NOT NULL,
        scope_type VARCHAR(24) NOT NULL,
        scope_owner_id VARCHAR(191) NULL,
        title VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        payload_json JSON NULL,
        action_path VARCHAR(512) NULL,
        occurred_at DATETIME(6) NOT NULL,
        created_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_notifications_org_id (org_id,id),
        UNIQUE KEY uq_billing_notifications_key (org_id,notification_key),
        KEY idx_billing_notifications_feed (org_id,occurred_at,id),
        KEY idx_billing_notifications_scope (org_id,scope_type,scope_owner_id,occurred_at,id),
        ${orgAccountFk('billing_notifications')}
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_notification_recipients (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        notification_id VARCHAR(191) NOT NULL,
        recipient_type VARCHAR(24) NOT NULL,
        recipient_key VARCHAR(191) NOT NULL,
        user_id VARCHAR(191) NULL,
        contact_id VARCHAR(191) NULL,
        email_snapshot VARCHAR(320) NULL,
        verification_state VARCHAR(24) NOT NULL,
        read_at DATETIME(6) NULL,
        created_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_notification_recipients_org_id (org_id,id),
        UNIQUE KEY uq_billing_notification_recipients_target (org_id,notification_id,recipient_key),
        KEY idx_billing_notification_recipients_user_feed (org_id,user_id,read_at,created_at),
        KEY idx_billing_notification_recipients_contact (org_id,contact_id,created_at),
        CONSTRAINT fk_billing_notification_recipients_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_notification_recipients_notification FOREIGN KEY (org_id,notification_id)
          REFERENCES billing_notifications(org_id,id),
        CONSTRAINT fk_billing_notification_recipients_contact FOREIGN KEY (org_id,contact_id)
          REFERENCES billing_contacts(org_id,id)
      )`,
    },
    {
      sql: `CREATE TABLE IF NOT EXISTS billing_notification_deliveries (
        id VARCHAR(191) NOT NULL,
        org_id VARCHAR(191) NOT NULL,
        notification_id VARCHAR(191) NOT NULL,
        recipient_id VARCHAR(191) NOT NULL,
        channel VARCHAR(24) NOT NULL,
        delivery_key VARCHAR(191) NOT NULL,
        status VARCHAR(24) NOT NULL DEFAULT 'pending',
        available_at DATETIME(6) NOT NULL,
        attempts INT UNSIGNED NOT NULL DEFAULT 0,
        lease_owner VARCHAR(191) NULL,
        lease_token VARCHAR(191) NULL,
        fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
        lease_expires_at DATETIME(6) NULL,
        provider_message_id VARCHAR(191) NULL,
        delivered_at DATETIME(6) NULL,
        last_error_code VARCHAR(96) NULL,
        last_error_at DATETIME(6) NULL,
        created_at DATETIME(6) NOT NULL,
        updated_at DATETIME(6) NOT NULL,
        PRIMARY KEY (id),
        UNIQUE KEY uq_billing_notification_deliveries_org_id (org_id,id),
        UNIQUE KEY uq_billing_notification_deliveries_once (org_id,notification_id,recipient_id,channel),
        UNIQUE KEY uq_billing_notification_deliveries_key (org_id,delivery_key),
        KEY idx_billing_notification_deliveries_claim (status,available_at,id),
        KEY idx_billing_notification_deliveries_lease (status,lease_expires_at,id),
        KEY idx_billing_notification_deliveries_recipient (org_id,recipient_id,status,created_at),
        CONSTRAINT fk_billing_notification_deliveries_org_account FOREIGN KEY (org_id)
          REFERENCES organization_billing_accounts(org_id),
        CONSTRAINT fk_billing_notification_deliveries_notification FOREIGN KEY (org_id,notification_id)
          REFERENCES billing_notifications(org_id,id),
        CONSTRAINT fk_billing_notification_deliveries_recipient FOREIGN KEY (org_id,recipient_id)
          REFERENCES billing_notification_recipients(org_id,id)
      )`,
    },
  ],
};
