'use strict';

/** Stable error identifiers returned by billing commands and adapters. */
const DOMAIN_ERROR_CODES = Object.freeze({
  INVALID_CONTRACT: 'BILLING_INVALID_CONTRACT',
  INVALID_AMOUNT: 'BILLING_INVALID_AMOUNT',
  AMOUNT_OVERFLOW: 'BILLING_AMOUNT_OVERFLOW',
  MIXED_ASSET: 'BILLING_MIXED_ASSET',
  MIXED_SCALE: 'BILLING_MIXED_SCALE',
  NOT_FOUND: 'BILLING_NOT_FOUND',
  FORBIDDEN: 'BILLING_FORBIDDEN',
  CONFLICT: 'BILLING_CONFLICT',
  IDEMPOTENCY_CONFLICT: 'BILLING_IDEMPOTENCY_CONFLICT',
  VERSION_CONFLICT: 'BILLING_VERSION_CONFLICT',
  PAYMENT_NOT_PENDING: 'BILLING_PAYMENT_NOT_PENDING',
  PAYMENT_AMOUNT_MISMATCH: 'BILLING_PAYMENT_AMOUNT_MISMATCH',
  DUPLICATE_PAYMENT_REFERENCE: 'BILLING_DUPLICATE_PAYMENT_REFERENCE',
  PERIOD_INVALID: 'BILLING_PERIOD_INVALID',
  PERIOD_NOT_FUNDED: 'BILLING_PERIOD_NOT_FUNDED',
  GRANT_NOT_AVAILABLE: 'BILLING_GRANT_NOT_AVAILABLE',
  GRANT_EXPIRED: 'BILLING_GRANT_EXPIRED',
  INSUFFICIENT_CREDITS: 'BILLING_INSUFFICIENT_CREDITS',
  USAGE_NOT_ENTITLED: 'BILLING_USAGE_NOT_ENTITLED',
  WORKSPACE_LIMIT_REACHED: 'BILLING_WORKSPACE_LIMIT_REACHED',
  ALLOCATION_INVALID: 'BILLING_ALLOCATION_INVALID',
  POSTPAID_DISABLED: 'BILLING_POSTPAID_DISABLED',
  POSTPAID_LIMIT_REACHED: 'BILLING_POSTPAID_LIMIT_REACHED',
  RESERVATION_NOT_FOUND: 'BILLING_RESERVATION_NOT_FOUND',
  RESERVATION_STATE_CONFLICT: 'BILLING_RESERVATION_STATE_CONFLICT',
  RETRYABLE_STORAGE: 'BILLING_RETRYABLE_STORAGE',
  RETRYABLE_CONCURRENCY: 'BILLING_RETRYABLE_CONCURRENCY',
  EXTERNAL_DELIVERY_FAILED: 'BILLING_EXTERNAL_DELIVERY_FAILED',
});

const ERROR_CODE_SET = new Set(Object.values(DOMAIN_ERROR_CODES));

class BillingDomainError extends Error {
  constructor(code, message, { retryable = false, details } = {}) {
    if (!ERROR_CODE_SET.has(code)) throw new TypeError(`Unknown billing domain error code: ${code}`);
    super(message || code);
    this.name = 'BillingDomainError';
    this.code = code;
    this.retryable = Boolean(retryable);
    if (details !== undefined) this.details = details;
  }
}

function isBillingDomainError(error, code) {
  return Boolean(error && error.name === 'BillingDomainError'
    && ERROR_CODE_SET.has(error.code)
    && (code === undefined || error.code === code));
}

module.exports = { DOMAIN_ERROR_CODES, BillingDomainError, isBillingDomainError };
